export const hobbyInitialState = {
  loading: false,
  success: false,
  deleteLoading: false,
  deleteSuccess: false,
  error: '',
  hobbies: [],
  modal: false,
  deleteModal: false,
  contentModal: false,
  toast: false,
  toastMessage: '',
  selected: '',
  queryWikiLoading: false,
  queryWikiSuccess: false,
  queryContent: '',
  queryError: '',
}
