export const HOBBY_LIST_REQUEST = 'HOBBY_LIST_REQUEST'
export const HOBBY_LIST_SUCCESS = 'HOBBY_LIST_SUCCESS'
export const HOBBY_LIST_ERROR = 'HOBBY_LIST_ERROR'
export const HOBBY_LIST_RESET = 'HOBBY_LIST_RESET'

export const HOBBY_CREATE_REQUEST = 'HOBBY_CREATE_REQUEST'
export const HOBBY_CREATE_SUCCESS = 'HOBBY_CREATE_SUCCESS'
export const HOBBY_CREATE_ERROR = 'HOBBY_CREATE_ERROR'
export const HOBBY_CREATE_RESET = 'HOBBY_CREATE_RESET'

export const HOBBY_DELETE_REQUEST = 'HOBBY_DELETE_REQUEST'
export const HOBBY_DELETE_SUCCESS = 'HOBBY_DELETE_SUCCESS'
export const HOBBY_DELETE_ERROR = 'HOBBY_DELETE_ERROR'

export const HOBBY_SHOW_MODAL = 'HOBBY_SHOW_MODAL'
export const HOBBY_HIDE_MODAL = 'HOBBY_HIDE_MODAL'
export const HOBBY_SHOW_DELETE_MODAL = 'HOBBY_SHOW_DELETE_MODAL'
export const HOBBY_HIDE_DELETE_MODAL = 'HOBBY_HIDE_DELETE_MODAL'
export const HOBBY_SHOW_CONTENT_MODAL = 'HOBBY_SHOW_CONTENT_MODAL'
export const HOBBY_HIDE_CONTENT_MODAL = 'HOBBY_HIDE_CONTENT_MODAL'

export const HOBBY_SHOW_TOAST = 'HOBBY_SHOW_TOAST'
export const HOBBY_HIDE_TOAST = 'HOBBY_HIDE_TOAST'
export const HOBBY_TOAST_MESSAGE = 'HOBBY_TOAST_MESSAGE'

export const HOBBY_SELECTED = 'HOBBY_SELECTED'

export const HOBBY_SORT_BY = 'HOBBY_SORT_BY'

export const HOBBY_QUERY_WIKI_REQUEST = 'HOBBY_QUERY_WIKI_REQUEST'
export const HOBBY_QUERY_WIKI_SUCCESS = 'HOBBY_QUERY_WIKI_SUCCESS'
export const HOBBY_QUERY_WIKI_ERROR = 'HOBBY_QUERY_WIKI_ERROR'
